GET http://localhost:3000/

### REGISTER
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "sachariaZ@email.com",
    "password": "sector19992"
}

### LOGIN
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "sachariaZ@email.com",
    "password": "sector19992"
}


### PROFILE
GET http://localhost:3000/profile
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhY2hhcmlhWkBlbWFpbC5jb20iLCJ1c2VyX2lkIjo2LCJpYXQiOjE2Mzg5MDMxNjcsImV4cCI6MTYzODkxMDM2N30.krTdgt9zYyJzfi2I3aPI0z_34Gej6njHTXOsaDWJhic

### USERS
POST http://localhost:3000/posts
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhY2hhcmlhWkBlbWFpbC5jb20iLCJ1c2VyX2lkIjo2LCJpYXQiOjE2Mzg5MDMxNjcsImV4cCI6MTYzODkxMDM2N30.krTdgt9zYyJzfi2I3aPI0z_34Gej6njHTXOsaDWJhic
Content-Type: application/json

{
    "title": "This is a great title",
    "content": "This is the great note"
}
### POSTS
GET http://localhost:3000/posts

###
GET http://localhost:3000/posts/123
###
POST http://localhost:3000/posts
###
GET http://localhost:3000/posts
###
PUT http://localhost:3000/posts/123
###
PATCH http://localhost:3000/posts/123
###
DELETE http://localhost:3000/posts/123
