X POST /api/users/login    Auth
X POST /api/users          Registration
X GET /api/user            Get current user
X PUT /api/user            Update current user
X GET /api/profiles/:username     auth optional

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Johannes",
    "lastName": "Svensson",
    "email": "johannes.svensson@email.com",
    "password": "johannes-secret"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "johannes.svensson@email.com",
    "password": "johannes-secret"
}

###
GET http://localhost:3000/user
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaGFubmVzLnN2ZW5zc29uQGVtYWlsLmNvbSIsInVzZXJfaWQiOjIsImlhdCI6MTYzOTA3MzkzNiwiZXhwIjoxNjM5MDgxMTM2fQ.UKTNt2DsUlqigYSL7_cu0A4EHzBjYTg17VLwbnF3T6k

###
PUT http://localhost:3000/user
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaGFubmVzLnN2ZW5zc29uQGVtYWlsLmNvbSIsInVzZXJfaWQiOjIsImlhdCI6MTYzOTA3MzkzNiwiZXhwIjoxNjM5MDgxMTM2fQ.UKTNt2DsUlqigYSL7_cu0A4EHzBjYTg17VLwbnF3T6k

{
    "firstName": "Emilia",
    "lastName": "Fredriksson"
}
###
GET http://localhost:3000/profiles/2
